#
# plugin config
#

# DEBUG MODE
debug: false

# DATABASE SETTING
Database:
  Jdbc: "postgresql"
  Host: ""
  Port: 5432
  Database: ""
  User: ""
  Pass: ""

Web:
  skinpath: ""
  skinmake: ""

Skin:
  cooldays: 3

Perm:
  chestlock: 5000
  shop: 3000

Price:
  min: 0
  max: 5000

Url:
  info: ""
  map: ""

Game:
  afk: 600000
  rank: 7200
  mode_change: 10800
  death: 200
  survival: world
  creative: home,city
  rain: 15

WorldEdit:
  task_delay: 2
  task_block: 10
  block_max: 40000