#
# plugin config
#

# DEBUG MODE
debug: false

# DATABASE SETTING
Database:
  Jdbc: "postgresql"
  Host: ""
  Port: 5432
  Database: ""
  User: ""
  Pass: ""

Web:
  skinpath: "/var/www/html/spigot/skin/data"
  skinmake: "http://kuro.host/spigot/skindisp.php"

Skin:
  cooldays: 3

Perm:
  chestlock: 5000

Price:
  min: 0
  max: 1000